# Generated by Django 4.2.28 on 2026-02-14 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        ("operations", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome único da categoria (ex: Bezerro, Novilho, Vaca)",
                        max_length=100,
                        unique=True,
                        verbose_name="Nome da Categoria",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional da categoria",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Categorias inativas não aparecem em novas operações, mas preservam histórico",
                        verbose_name="Ativa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Animal",
                "verbose_name_plural": "Categorias de Animais",
                "db_table": "animal_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FarmStockBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Saldo atual de animais nesta fazenda/categoria",
                        verbose_name="Quantidade Atual",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0,
                        help_text="Controle de concorrência otimista (incrementado a cada atualização)",
                        verbose_name="Versão",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp da última modificação no saldo",
                        verbose_name="Última Atualização",
                    ),
                ),
                (
                    "animal_category",
                    models.ForeignKey(
                        help_text="Tipo/categoria dos animais",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="inventory.animalcategory",
                        verbose_name="Categoria de Animal",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="Fazenda onde os animais estão localizados",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="farms.farm",
                        verbose_name="Fazenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saldo de Estoque",
                "verbose_name_plural": "Saldos de Estoque",
                "db_table": "farm_stock_balances",
                "ordering": ["farm__name", "animal_category__name"],
            },
        ),
        migrations.CreateModel(
            name="AnimalMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("ENTRADA", "ENTRADA"), ("SAIDA", "SAIDA")],
                        help_text="ENTRADA (aumenta saldo) ou SAÍDA (diminui saldo)",
                        max_length=20,
                        verbose_name="Tipo de Movimento",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("NASCIMENTO", "NASCIMENTO"),
                            ("COMPRA", "COMPRA"),
                            ("MANEJO_IN", "MANEJO_IN"),
                            ("MUDANCA_CATEGORIA_IN", "MUDANCA_CATEGORIA_IN"),
                            ("DESMAME", "DESMAME"),
                            ("MORTE", "MORTE"),
                            ("VENDA", "VENDA"),
                            ("ABATE", "ABATE"),
                            ("DOACAO", "DOACAO"),
                            ("MANEJO_OUT", "MANEJO_OUT"),
                            ("MUDANCA_CATEGORIA_OUT", "MUDANCA_CATEGORIA_OUT"),
                        ],
                        help_text="Operação específica que gerou esta movimentação",
                        max_length=30,
                        verbose_name="Tipo de Operação",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantidade de animais movimentados (sempre positiva)",
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Momento em que a operação foi realizada",
                        verbose_name="Data/Hora da Operação",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados adicionais da operação em formato JSON. Exemplos: peso, preço, observações, lote, etc.",
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp de criação do registro no sistema",
                        verbose_name="Data de Registro",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP de origem da requisição",
                        null=True,
                        verbose_name="Endereço IP",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cliente envolvido na operação (vendas/doações)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="operations.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Usuário que registrou esta operação",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animal_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado Por",
                    ),
                ),
                (
                    "death_reason",
                    models.ForeignKey(
                        blank=True,
                        help_text="Causa da morte do animal",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="operations.deathreason",
                        verbose_name="Motivo da Morte",
                    ),
                ),
                (
                    "farm_stock_balance",
                    models.ForeignKey(
                        help_text="Registro de saldo afetado por esta movimentação",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.farmstockbalance",
                        verbose_name="Saldo de Estoque",
                    ),
                ),
                (
                    "related_movement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Movimento vinculado (saída/entrada em operações compostas)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reverse_related_movement",
                        to="inventory.animalmovement",
                        verbose_name="Movimento Relacionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Animal",
                "verbose_name_plural": "Movimentações de Animais",
                "db_table": "animal_movements",
                "ordering": ["-timestamp", "-created_at"],
                "permissions": [
                    (
                        "view_movement_audit",
                        "Pode visualizar auditoria de movimentações",
                    ),
                    (
                        "recalculate_stock",
                        "Pode recalcular saldos a partir do histórico",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="animalcategory",
            index=models.Index(fields=["name"], name="animal_cate_name_ddd237_idx"),
        ),
        migrations.AddIndex(
            model_name="animalcategory",
            index=models.Index(
                fields=["is_active", "name"], name="animal_cate_is_acti_6c749a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmstockbalance",
            index=models.Index(
                fields=["farm", "animal_category"],
                name="farm_stock__farm_id_43482d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="farmstockbalance",
            index=models.Index(
                fields=["animal_category", "farm"],
                name="farm_stock__animal__502a93_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="farmstockbalance",
            index=models.Index(
                fields=["current_quantity"], name="farm_stock__current_c28d59_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="farmstockbalance",
            constraint=models.UniqueConstraint(
                fields=("farm", "animal_category"), name="unique_farm_category_balance"
            ),
        ),
        migrations.AddConstraint(
            model_name="farmstockbalance",
            constraint=models.CheckConstraint(
                check=models.Q(("current_quantity__gte", 0)),
                name="stock_balance_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="animalmovement",
            index=models.Index(
                fields=["farm_stock_balance", "timestamp"],
                name="animal_move_farm_st_aea629_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="animalmovement",
            index=models.Index(
                fields=["farm_stock_balance", "created_at"],
                name="animal_move_farm_st_464160_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="animalmovement",
            index=models.Index(
                fields=["operation_type", "timestamp"],
                name="animal_move_operati_e0a7c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="animalmovement",
            index=models.Index(
                fields=["timestamp"], name="animal_move_timesta_92740d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animalmovement",
            index=models.Index(
                fields=["created_at"], name="animal_move_created_94b4c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animalmovement",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="animal_move_created_8dc871_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="animalmovement",
            index=models.Index(
                fields=["client", "timestamp"], name="animal_move_client__d8eb38_idx"
            ),
        ),
    ]
