# Generated by Django 4.2.28 on 2026-03-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animalcategory",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Categoria de Animal",
                "verbose_name_plural": "Categorias de Animais",
            },
        ),
        migrations.RemoveIndex(
            model_name="animalcategory",
            name="animal_cate_is_acti_6c749a_idx",
        ),
        migrations.AddField(
            model_name="animalcategory",
            name="display_order",
            field=models.IntegerField(
                default=100,
                help_text="Ordem de exibição nas listagens (menor = primeiro)",
                verbose_name="Ordem de Exibição",
            ),
        ),
        migrations.AddField(
            model_name="animalcategory",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Categorias do sistema são pré-definidas e não podem ser excluídas ou ter o slug alterado.",
                verbose_name="Categoria do Sistema",
            ),
        ),
        migrations.AddField(
            model_name="animalcategory",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Identificador único para referência no código. Preenchido automaticamente para categorias do sistema. Deixe em branco para categorias customizadas.",
                null=True,
                unique=True,
                verbose_name="Slug (Identificador Programático)",
            ),
        ),
        migrations.AlterField(
            model_name="animalmovement",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("NASCIMENTO", "NASCIMENTO"),
                    ("COMPRA", "COMPRA"),
                    ("MANEJO_IN", "MANEJO_IN"),
                    ("MUDANCA_CATEGORIA_IN", "MUDANCA_CATEGORIA_IN"),
                    ("DESMAME_IN", "DESMAME_IN"),
                    ("SALDO", "SALDO"),
                    ("MORTE", "MORTE"),
                    ("VENDA", "VENDA"),
                    ("ABATE", "ABATE"),
                    ("DOACAO", "DOACAO"),
                    ("MANEJO_OUT", "MANEJO_OUT"),
                    ("MUDANCA_CATEGORIA_OUT", "MUDANCA_CATEGORIA_OUT"),
                    ("DESMAME_OUT", "DESMAME_OUT"),
                ],
                help_text="Operação específica que gerou esta movimentação",
                max_length=30,
                verbose_name="Tipo de Operação",
            ),
        ),
        migrations.AddIndex(
            model_name="animalcategory",
            index=models.Index(fields=["slug"], name="animal_cate_slug_d7a0b4_idx"),
        ),
        migrations.AddIndex(
            model_name="animalcategory",
            index=models.Index(
                fields=["is_active", "display_order", "name"],
                name="animal_cate_is_acti_fe6cea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="animalcategory",
            index=models.Index(
                fields=["is_system"], name="animal_cate_is_syst_6e73eb_idx"
            ),
        ),
    ]
