# Generated by Django 4.2.28 on 2026-03-01 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0002_alter_animalcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalmovement",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("NASCIMENTO", "Nascimento"),
                    ("COMPRA", "Compra"),
                    ("MANEJO_IN", "Manejo (Entrada)"),
                    ("MUDANCA_CATEGORIA_IN", "Mud. Categoria (Entrada)"),
                    ("DESMAME_IN", "Mud. Categoria (Entrada)"),
                    ("SALDO", "Ajuste de Saldo"),
                    ("MORTE", "Morte"),
                    ("VENDA", "Venda"),
                    ("ABATE", "Abate"),
                    ("DOACAO", "Doação"),
                    ("MANEJO_OUT", "Manejo (Saída)"),
                    ("MUDANCA_CATEGORIA_OUT", "Mud. Categoria (Saída)"),
                    ("DESMAME_OUT", "Desmame (Saída)"),
                ],
                help_text="Operação específica que gerou esta movimentação",
                max_length=30,
                verbose_name="Tipo de Operação",
            ),
        ),
        migrations.CreateModel(
            name="AnimalMovementCancellation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Cancelado em"
                    ),
                ),
                (
                    "quantity_restored",
                    models.PositiveIntegerField(verbose_name="Quantidade estornada"),
                ),
                (
                    "balance_before",
                    models.PositiveIntegerField(verbose_name="Saldo antes do estorno"),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(verbose_name="Saldo após o estorno"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Observações"
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellations_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelado por",
                    ),
                ),
                (
                    "movement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellation",
                        to="inventory.animalmovement",
                        verbose_name="Ocorrência cancelada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cancelamento de Ocorrência",
                "verbose_name_plural": "Cancelamentos de Ocorrências",
                "db_table": "animal_movement_cancellations",
                "ordering": ["-cancelled_at"],
                "indexes": [
                    models.Index(
                        fields=["cancelled_at"], name="animal_move_cancell_3bb6b0_idx"
                    ),
                    models.Index(
                        fields=["cancelled_by", "cancelled_at"],
                        name="animal_move_cancell_58cee2_idx",
                    ),
                ],
            },
        ),
    ]
