# Generated by Django 4.2.28 on 2026-03-03 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operations", "0001_initial"),
        ("inventory", "0003_alter_animalmovement_operation_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animalmovementcancellation",
            options={
                "ordering": ["-cancelled_at"],
                "verbose_name": "Cancelamento de Movimentação",
                "verbose_name_plural": "Cancelamentos de Movimentações",
            },
        ),
        migrations.AlterField(
            model_name="animalmovementcancellation",
            name="movement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancellation",
                to="inventory.animalmovement",
                verbose_name="Movimentação cancelada",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalAnimalMovementCancellation",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="Cancelado em",
                    ),
                ),
                (
                    "quantity_restored",
                    models.PositiveIntegerField(verbose_name="Quantidade estornada"),
                ),
                (
                    "balance_before",
                    models.PositiveIntegerField(verbose_name="Saldo antes do estorno"),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(verbose_name="Saldo após o estorno"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Observações"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.animalmovement",
                        verbose_name="Movimentação cancelada",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Cancelamento de Movimentação",
                "verbose_name_plural": "historical Cancelamentos de Movimentações",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAnimalMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("ENTRADA", "ENTRADA"), ("SAIDA", "SAIDA")],
                        help_text="ENTRADA (aumenta saldo) ou SAÍDA (diminui saldo)",
                        max_length=20,
                        verbose_name="Tipo de Movimento",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("NASCIMENTO", "Nascimento"),
                            ("COMPRA", "Compra"),
                            ("MANEJO_IN", "Manejo (Entrada)"),
                            ("MUDANCA_CATEGORIA_IN", "Mud. Categoria (Entrada)"),
                            ("DESMAME_IN", "Mud. Categoria (Entrada)"),
                            ("SALDO", "Ajuste de Saldo"),
                            ("MORTE", "Morte"),
                            ("VENDA", "Venda"),
                            ("ABATE", "Abate"),
                            ("DOACAO", "Doação"),
                            ("MANEJO_OUT", "Manejo (Saída)"),
                            ("MUDANCA_CATEGORIA_OUT", "Mud. Categoria (Saída)"),
                            ("DESMAME_OUT", "Desmame (Saída)"),
                        ],
                        help_text="Operação específica que gerou esta movimentação",
                        max_length=30,
                        verbose_name="Tipo de Operação",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantidade de animais movimentados (sempre positiva)",
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Momento em que a operação foi realizada",
                        verbose_name="Data/Hora da Operação",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados adicionais da operação em formato JSON. Exemplos: peso, preço, observações, lote, etc.",
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP de origem da requisição",
                        null=True,
                        verbose_name="Endereço IP",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Cliente envolvido na operação (vendas/doações)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="operations.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Usuário que registrou esta operação",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado Por",
                    ),
                ),
                (
                    "death_reason",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Causa da morte do animal",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="operations.deathreason",
                        verbose_name="Motivo da Morte",
                    ),
                ),
                (
                    "farm_stock_balance",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Registro de saldo afetado por esta movimentação",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.farmstockbalance",
                        verbose_name="Saldo de Estoque",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_movement",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Movimento vinculado (saída/entrada em operações compostas)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.animalmovement",
                        verbose_name="Movimento Relacionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Movimentação de Animal",
                "verbose_name_plural": "historical Movimentações de Animais",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
