# Generated by Django 4.2.30 on 2026-04-28 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_animalmovementcancellation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalmovement",
            name="timestamp",
            field=models.DateField(
                db_index=True,
                default=datetime.date.today,
                help_text="Data em que a operação foi realizada",
                verbose_name="Data da Operação",
            ),
        ),
        migrations.AlterField(
            model_name="historicalanimalmovement",
            name="timestamp",
            field=models.DateField(
                db_index=True,
                default=datetime.date.today,
                help_text="Data em que a operação foi realizada",
                verbose_name="Data da Operação",
            ),
        ),
    ]
