# Generated by Django 4.2.28 on 2026-02-14 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome único identificador da fazenda",
                        max_length=200,
                        unique=True,
                        verbose_name="Nome da Fazenda",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Fazendas inativas não aparecem em operações, mas preservam histórico",
                        verbose_name="Ativa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fazenda",
                "verbose_name_plural": "Fazendas",
                "db_table": "farms",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="farms_name_8cb391_idx"),
                    models.Index(
                        fields=["is_active", "name"], name="farms_is_acti_5cc11b_idx"
                    ),
                ],
            },
        ),
    ]
