# Generated by Django 4.2.28 on 2026-02-14 05:26

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeathReason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome do motivo da morte (ex: Doença, Predador, Natural)",
                        max_length=100,
                        unique=True,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do motivo",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Motivos inativos não aparecem em novas operações, mas preservam histórico",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Motivo de Morte",
                "verbose_name_plural": "Motivos de Morte",
                "db_table": "death_reasons",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="death_reaso_name_5bd142_idx"),
                    models.Index(
                        fields=["is_active", "name"],
                        name="death_reaso_is_acti_05e88f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único universal",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome completo ou razão social do cliente",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        blank=True,
                        help_text="CPF (000.000.000-00) ou CNPJ (00.000.000/0000-00)",
                        max_length=18,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Formato inválido. Use: 000.000.000-00 (CPF) ou 00.000.000/0000-00 (CNPJ)",
                                regex="^(\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}|\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2})?$",
                            )
                        ],
                        verbose_name="CPF/CNPJ",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Telefone de contato",
                        max_length=20,
                        null=True,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email de contato",
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Endereço completo do cliente",
                        null=True,
                        verbose_name="Endereço",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Clientes inativos não aparecem em novas operações, mas preservam histórico",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "clients",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="clients_name_0bc5f0_idx"),
                    models.Index(
                        fields=["cpf_cnpj"], name="clients_cpf_cnp_b6455e_idx"
                    ),
                    models.Index(
                        fields=["is_active", "name"], name="clients_is_acti_a4880f_idx"
                    ),
                ],
            },
        ),
    ]
